name: Carepack Deployment Workflow

on:
  merge-group:
    types: [checks_requested]
  push:
    branches: ["main"]
  pull_request:
    branches: [ "main" ]

jobs:   
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2  
